### ISSUE TITLE
mwc radio with mwc formfield, the radio doesn't toggle when clicking on label in mobile devices  

### ISSUE THREAD

**Issue by siva-bathula** [material-components/material-components-web-components#1122] opened 2020-04-14 10:48 UTC
I have a group of mwc radio's in conjunction with mwc formfield's. In mobile devices(both mobile and chrome developer tools) when clicking on formfield's label creates a ripple on the radio but it doesn't check or uncheck the button.

**To Reproduce**
1. Create a group of mwc-radio inside mwc-formfield's inside a page
2. Open page mobile browser/chrome developer tools
3. click on formfield label.
4. The radio should get toggled to check/uncheck, but it only creates a ripple but doesnt toggle.

**Expected behavior**
radio button should check/uncheck.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3694427/79216625-22488580-7e6b-11ea-846c-16080594ae2b.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0

**Comment by asyncLiz** [comment] 2020-04-15 18:04
Hi! Can you add a reproduction link? I tried clicking on the labels at http://mwc-demos.glitch.me/demos/formfield.html and it changes the radio for me on desktop and mobile.

Does the demo site work for you in your environment?

I tested Chrome 80 (OS X), Edge 80 (Win 10), and Chrome on Android.

**Comment by rwestlund** [comment] 2020-04-15 18:18
This exact thing is happening to us too, but we can't reproduce the issue with a simple example. We haven't figured out what's causing it.

CC @yujiri8

**Comment by siva-bathula** [comment] 2020-04-16 06:06
I am unable to reproduce the issue on codepen. https://codepen.io/bathu/pen/abvdQoG
It works as expected, maybe something else is the issue

**Comment by dfreedm** [comment] 2020-04-22 22:06
Ok, closing the issue then. If you find a good reproduction, we can reopen this!

**Closed by dfreedm** 2020-04-22 22:06 UTC
Labels: Feedback Requested, Focus Area: Components, Type: Bug

**Comment by siva-bathula** [comment] 2020-04-23 07:46
Its again failing. This time clicking on radio also doesn't work. I didn't change any code, so I wonder what must have changed. @dfreedm can you check this link  https://codepen.io/bathu/pen/abvdQoG to see if it works properly?

**Comment by ednigar** [comment] 2020-09-10 10:49
Hi, I have the same problem but with checkboxes. There's any solution to this? I saw that the problem is that .mdc-checkbox doesn't add class mdc-checkbox--selected when cliking in .mdc-label in mobile devices.
