### ISSUE TITLE
[mwc-tab-bar] Tab content

### ISSUE THREAD

**Issue by marcoliceti** [material-components/material-components-web-components#2361] opened 2021-04-29 15:18 UTC
Hi, suppose you have something like this:

```html
<mwc-tab-bar>
  <mwc-tab label="One">
    <p>Foo</p>
  </mwc-tab>
  <mwc-tab label="Two">
    <p>Bar</p>
  </mwc-tab>
</mwc-tab-bar>
```

Normally, I'd expect that selecting tab "One" would display "Foo", while selecting tab "Two" would display "Bar". Unfortunately, that's not the case.

Looking at the source code, it seems that this is actually the expected behavior, and tab content should be handled outsided of an `mwc-tab` / `mwc-tab-bar`... am I right?

**Comment by taylor-vann** [comment] 2021-04-30 02:04
Hey @marcoliceti thanks for submitting!

You are correct, that is intended behavior. To see a more detailed explanation, click [here](https://github.com/material-components/material-components-web-components/tree/master/packages/tab-bar#mwc-tab-bar-).

Children of `<mwc-tab-bar>` are expected to be accompanied by `hasImageIcon ` to set an icon of some sort. You can find more details [here](https://github.com/material-components/material-components-web-components/tree/master/packages/tab-bar#image--slotted-icons) :)

Hope it helps! Gonna close this issue because it's expected behavior!

**Closed by taylor-vann** 2021-04-30 02:04 UTC
Labels: Focus Area: Components, Type: Bug
