### ISSUE TITLE
[mwc-button] enforces opinionated approach to implementing icons

### ISSUE THREAD

**Issue by yinonov** [material-components/material-components-web-components#2343] opened 2021-04-26 09:36 UTC
**Is your feature request related to a problem? Please describe.**
Customization of icons in `mwc-button` (and in mwc in general) demands practicing the font-base icons approach while this is an opinionated approach and there are other practices consuming apps might already implement (svg, svg inlined, images etc'...)

**Describe the solution you'd like**
allow overriding high level declaration of how icons should be rendered. (the property **icon** should be preserved and used)
instead of
```html
<mwc-button>
  #shadow-root
    <button>
      <mwc-ripple>
      <span class="leading-icon">
      ...
```
result in
```html
<mwc-button>
  #shadow-root
    <button>
      <mwc-ripple>
      <my-icon>
```

**Comment by taylor-vann** [comment] 2021-04-26 19:08
hey @yinonov thanks for submitting!

Font icons can overridden with the `icon` and `trailing-icon` slots for `mwc-button`.

It'd be similar to something like below:
```
<mwc-button>
  <my-icon slot="icon"></my-icon>
</mwc-button>
```

They're referenced [here](https://github.com/material-components/material-components-web-components/blob/master/packages/button/README.md#slots).

Thanks for pointing this out. Going to close this issue because I think this is "working as intended" while still providing you with a solution :)

**Closed** 2021-04-26 19:09 UTC
Labels: Focus Area: Components, Type: Feature
