### ISSUE TITLE
mwc-tab applies wrong styles to slotted elements

### ISSUE THREAD

**Issue by ergo** [material-components/material-components-web-components#286] opened 2019-06-23 14:26 UTC
Hi,

when `mwc-tab` is used like this:

    <mwc-tab-bar>
      <mwc-tab label="one"></mwc-tab>
      <mwc-tab label="two"></mwc-tab>
      <mwc-tab label="three"></mwc-tab>
    </mwc-tab-bar>

Everything is working as intended, I can apply color via css var `--mdc-theme-primary: red;`, and it  gets propagated correctly.

However if I use tabs like this:

    <mwc-tab-bar>
      <mwc-tab>One</mwc-tab>
      <mwc-tab>Two</mwc-tab>
      <mwc-tab>Three</mwc-tab>
    </mwc-tab-bar>

The text will not become red.

**Comment by e111077** [comment] 2019-11-14 04:02
Unfortunately using the slot in this use case is not what the slot was intended for. 

The slot was intended for being used as a method to insert an image icon via an `<img>` or `<svg>` etc. (as a matter of fact, this use case does not work, so we will have to make a fix for this).

**Comment by e111077** [comment] 2019-11-14 04:18
related #628

**Closed by e111077** 2019-11-14 04:18 UTC
Labels: Area: Styling, Component: Tab, Type: Bug
