### ISSUE TITLE
Button, switch and checkbox cause Safari to crash

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-components-web-components#1865] opened 2020-10-01 13:45 UTC
**Describe the bug**
When clicking a button, switch or checkbox in Safari (v >= 14) the tab crashes.

**To Reproduce**
1. Go to https://material-components.github.io/material-components-web-components/demos/button/ on Safari
2. Click on any non-disabled button
3. See error

**Expected behavior**
Would expect the browser to keep working.

**Screenshots**
https://www.screencast.com/t/VBZaIqB1Ynqk

**Browser Version (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14

**Comment by RuarriS** [comment] 2020-10-01 15:31
This is a known issue with Safari and `delegateFocus: true` 

See #1720 for some workarounds.

**Comment by dfreedm** [comment] 2020-10-01 22:39
This is a duplicate of #1720

**Closed by dfreedm** 2020-10-01 22:39 UTC
Labels: Focus Area: Components, Type: Bug
