### ISSUE TITLE
mwc-drawer: can't change background-color and border-color

### ISSUE THREAD

**Issue by frankiefu** [material-components/material-components-web-components#188] opened 2019-01-15 18:49 UTC
Currently there is no easy way to change the default background-color (`#fff`) and border-color (`rgba(0,0,0,.12)`).

**Comment by azakus** [comment] 2019-11-08 00:16
Related to https://github.com/material-components/material-components-web/issues/5242

**Comment by govis** [comment] 2020-02-07 21:05
Priority: High since Jan 15, 2019 and it's still not possible to change the drawer background color

**Comment by Alos** [comment] 2020-12-01 17:06
Would love if this issue is fixed 👍

**Comment by asyncLiz** [comment] 2021-02-17 18:40
Going to close this as a duplicate of https://github.com/material-components/material-components-web-components/issues/953, which has more information related to the issue. Subscribe to that for further updates!

**Closed by asyncLiz** 2021-02-17 18:40 UTC
Labels: Component: Drawer, Focus Area: Components, Severity: Medium, Styling, Type: Bug
