### ISSUE TITLE
mwc-select: label position is lower than all other inputs

### ISSUE THREAD

**Issue by aarondrabeck** [material-components/material-components-web-components#1276] opened 2020-05-07 16:39 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/9825025/81320773-f5912380-904e-11ea-957d-595da1dcb3d5.png)

**Browser Version (please complete the following information):**
All

**Comment by asyncLiz** [comment] 2020-05-07 17:16
Thanks for noticing! Confirmed on our demo page. The textfield's floating label positioning values recently were updated, so I bet that's probably a good place to start.

It'd also be a good idea to confirm if this is only in MWC or if it's in MDC as well. Might need to bump MWC's dependencies if it's fixed in MDC.

**Comment by allan-chen** [comment] 2020-05-07 18:04
Surprise surprise. Somehow it has to do with `font-family: Roboto, sans-serif` on the notched outline. Removing this solves the issue.

**Comment by allan-chen** [comment] 2020-05-07 18:07
After removing all transforms and setting `left: 0; top: 0` for clarity:

With `font-family: Roboto, sans-serif`: <img width="675" alt="Screen Shot 2020-05-07 at 11 05 18 AM" src="https://user-images.githubusercontent.com/7828061/81329056-cb416500-9052-11ea-8b2c-4c04a028cb26.png">

Without:
<img width="644" alt="Screen Shot 2020-05-07 at 11 06 11 AM" src="https://user-images.githubusercontent.com/7828061/81329116-e9a76080-9052-11ea-92b7-718bf63f204a.png">

**Comment by allan-chen** [comment] 2020-05-07 18:10
This is just inherited from body. The font family is set separately in the actual label element. Wonder if we can remove this on the notched outline which is its parent.

**Comment by allan-chen** [comment] 2020-05-07 18:22
More notes: this seems to only occur on "required" variant

**Comment by allan-chen** [comment] 2020-05-07 18:50
More notes: this doesn't seem to happen in vanilla MDC component

**Comment by allan-chen** [comment] 2020-05-08 04:41
The root cause is actually the label being `inline-flex` instead of `inline-block`. PR created to fix

**Closed** 2020-05-08 17:38 UTC
Labels: Component: Select, Focus Area: Components, Severity: Medium, Type: Bug, Why: improve ergonomics
