### ISSUE TITLE
Drawer prevents sticky navbar

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1541] opened 2020-07-17 21:08 UTC
**Describe the bug**
I found out that it is not possible to create a `sticky navigation bar` or any other `sticky children` due to the `mwc-drawer` using the following overflow property:
.mdc-drawer-app-content {  overflow: auto;  flex: 1;}

According to the following link and to my personal experiments the use of `overflow: auto` prevents the use of `sticky positioning`:
https://university.webflow.com/article/position-sticky#:~:text=That%20can%20happen%20for%20many,do%20not%20support%20sticky%20positioning.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a basic `mwc-drawer` skeleton.
2. Create an `navbar` div with the `position` set to `sticky`.
3. Observe how the sticky behaviour is not respected.

**Expected behavior**
The navigation bar should stick to the top of the screen.

**Comment by asyncLiz** [comment] 2020-07-17 22:35
Thanks for the bug!

`position: sticky` does work with `<mwc-drawer>`, take a look at this demo: https://jsbin.com/rotefefasu/edit?html,output

Oftentimes the most common problem of `sticky` issues is forgetting to set top/left/bottom/right. If you want your navigation bar to stick to the top of the screen after scrolling, you should set `top: 0` on the navigation bar itself.

Closing since this is working, but feel free to comment if you're still having trouble! A jsbin with your use case would help us understand where the problem is.

**Closed by asyncLiz** 2020-07-17 22:35 UTC
Labels: Focus Area: Components, Type: Bug

**Comment by aress31** [comment] 2020-07-17 23:34
@asyncLiz please see the following code sandbox:

https://codesandbox.io/s/nostalgic-voice-b67ok?file=/src/app.ts

**Comment by easterday** [comment] 2020-08-15 02:40
Thanks for the example @asyncLiz!  

I was also running into a similar problem with .mdc-drawer-app-content setting overflow: auto in situations where you want the height of the mwc-drawer to be set by it's content rather than set explicitly:  https://jsbin.com/coruyacofe/5/edit?html,output  Removing the overflow: auto makes the sticky element behave as desired.
