### ISSUE TITLE
mwc-switch doesn't fire change events

### ISSUE THREAD

**Issue by ErikHellman** [material-components/material-components-web-components#161] opened 2018-11-08 19:23 UTC
The `mwc-switch` doesn't seem to fire any change events. When I use it like this, nothing is printed in the console. 

```
<mwc-switch @change="${console.log}"></mwc-switch>
```

**Comment by ErikHellman** [comment] 2018-11-09 07:12
I noted that if I use `@click` instead of `@change`, I get an event. But that doesn't feel like the right type of event to listen for on a switch.

**Comment by gdavalos** [comment] 2018-11-13 22:29
I'm having the exact same problem, click also doesn't work as expected since it fires before the `checked` property is updated

**Comment by frankiefu** [comment] 2019-03-07 19:06
duplicate of https://github.com/material-components/material-components-web-components/issues/63

**Closed by frankiefu** 2019-03-07 19:06 UTC
Labels: Type: Bug, Type: Question

**Comment by comp500** [comment] 2022-11-08 21:53
`mwc-switch` has since been changed to not dispatch a `change` event (on purpose? not sure why); see https://github.com/material-components/material-web/commit/c527e93b0df57a5f982e834f6eadcb3d8839920b

**Comment by peschee** [comment] 2022-11-29 17:06
@comp500 The changelog states: "use `click` events". So I guess that's the reason.
