### ISSUE TITLE
mwc-drawer does not open and close correctly

### ISSUE THREAD

**Issue by snelson25** [material-components/material-components-web-components#465] opened 2019-09-10 19:12 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10

**What browser(s) is this bug affecting:**

Chrome Version 76.0.3809.132 (Official Build) (64-bit)
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Current behavior:**

Drawer content does not open and close.  Drawer content is always present.  App content is shifted to right when drawer content is opened.

**Expected behavior:**

The drawer should open and close.  

**Steps to reproduce:**

Test code at: 
https://stackblitz.com/edit/r9jqqp-gual9n?file=my-element.js

To reproduce, click navigation button in top left corner multiple times.

**Comment by graynorton** [comment] 2019-11-07 21:54
It appears that the code in the reproduction case uses an attribute called `dismissable`, rather than `dismissible`, so this is not a bug as written.

However, the README for this component does itself say "dismissable" in one or more places, so that should be cleaned up before closing this issue.

**Closed** 2019-11-12 23:05 UTC
Labels: Component: Drawer
