### ISSUE TITLE
[mwc-radio & mwc-formfield] middle alignement issue

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#611] opened 2019-11-06 19:02 UTC
When using `mwc-radio` in a `mwc-formfield` the label is not properly aligned with the radio button.

reproduction : [https://mwc-radio-and-mwc-formfield-alignment.glitch.me/](https://mwc-radio-and-mwc-formfield-alignment.glitch.me/) (with hotfix)

**Comment by aomarks** [comment] 2019-11-06 19:17
That glitch link doesn't work for me (CORS error relating to bu.edu), but doe shttps://github.com/material-components/material-components-web-components/issues/380 describe the same issue you are seeing?

**Comment by vdegenne** [comment] 2019-11-06 20:21
Yes that's the issue i'm referring to.

> 2. The radio label is not vertically aligned with the radio button (red line).

for now I am using this quick fix :

```html
<mwc-formfield label="radio">
  <mwc-radio style="display:flex"></mwc-radio>
</mwc-formfield>
```

**Comment by aomarks** [comment] 2019-11-06 20:24
Thanks for confirming, closing as dupe of https://github.com/material-components/material-components-web-components/issues/380

**Comment by e111077** [comment] 2019-11-14 01:49
reclosing because this seems to actually be a. dupe of #380

**Closed by e111077** 2019-11-14 01:49 UTC
