### ISSUE TITLE
[Button] Outlined outline color should not be set to primary but 12% on-surface 

### ISSUE THREAD

**Issue by yasmineevjen** [material-components/material-components-web-components#1125] opened 2020-04-14 18:24 UTC
The Material spec notes that the outline color of an outlined button should be set to on-surface at 12%, but we seem to set it as primary.

**Comment by isochronous** [comment] 2020-04-21 21:27
Is this not a duplicate of #961 ?

**Comment by dfreedm** [comment] 2020-04-21 21:29
Oh yeah, sure is! I'll close this as a dupe of #961

**Closed by dfreedm** 2020-04-21 21:29 UTC
Labels: Component: Button, Focus Area: Components, Severity: Medium, Type: Bug, Unplanned
