### ISSUE TITLE
mwc-radio don't fire events

### ISSUE THREAD

**Issue by LostInBrittany** [material-components/material-components-web-components#77] opened 2018-07-17 22:06 UTC
I am used to the *typical* Web Components patter of attributes-in/events-out, so when I tried to use mwc-radio I kinda expected it to fire a `change` event when its state change, but it doesn't...

I feel a bit lost about the intended way to use it. Let's say I have a radio group :+1: 
```
<div>
        <mwc-radio value='toto'  name='raaadio'></mwc-radio><div>Toto</div>
        <mwc-radio value='titi' name='raaadio'></mwc-radio><div>Titi</div>
        <mwc-radio value='tata' name='raaadio'></mwc-radio><div>Tata</div>
</div>
```
How can I detect a change in the selected radio button? 
I have tested listening for `change` event in each button and in the div, without success...

Thanks in advance!

**Comment by azakus** [comment] 2018-08-06 21:38
We need to have a comprehensive set of documentation for a component's events, both from the material-components-web baseclass, and any we add.

**Comment by kenchris** [comment] 2018-09-18 12:48
@LostInBrittany btw I believe you are supposed to use mwc-formfield for adding the label:

```
      <mwc-formfield label="0˚">
        <mwc-radio id="o.1" name="o" on-click="lockOrientation" data-args="portrait-primary" checked></mwc-radio>
      </mwc-formfield>
 ```

**Comment by balloob** [comment] 2018-10-09 21:21
Can confirm that this also affects `<mwc-switch>` , no `change` events fired

**Comment by azakus** [comment] 2018-10-09 22:33
Duplicate of #63

**Closed by azakus** 2018-10-09 22:33 UTC
Labels: duplicate
