### ISSUE TITLE
Use :focus-visible instead of :focus

### ISSUE THREAD

**Issue by lazylazyllama** [material-components/material-components-web-components#1847] opened 2020-09-25 18:46 UTC
**Is your feature request related to a problem? Please describe.**
When adding css :focus styles you get the ability to navigate the app via keyboard but have the drawback, that a button will also get focused if you Klick on it. So the focused style will stay after you clicked on it. This looks a bit off and makes the app fell "like a website" as native applications don't have these issues.

**Describe the solution you'd like**
When we use :focus-visible instead of :focus the extra styling will only be activated by navigating with a keyboard. So we get the advantages to make our app keyboard friendly but without the disadvantage of having weird side effects while using the mouse.

**Additional context**
Obviously there are exceptions like the input field, where we would like to keep it as is and have the focused stylings even when clicked by a mouse.

**Comment by asyncLiz** [comment] 2020-09-25 20:40
Thanks for the suggestion!

As Material Design exists today, focus styles should be applied and remain applied on the _web platform_ when clicking or tapping components. This is because the web, unlike native, maintains focus on an element after clicking on it and does not remove focus until another element is clicked on.

While the web platform can be used within the native platform, it's important to remember that some of these behaviors are inherently different, and it's not the responsibility of the web to imitate the native platform _under certain conditions_. Keep in mind that some native platforms will introduce focus styling when they do not normally have them, such as when a pointer is attached in iOS.

That being said, our designers are currently investigating new focus styles to make the visual distinction between hovering and focusing much clearer on the web and on native platforms, so the discrepancy between the two should be reduced in the future.

I'm going to close this issue since the focus styles are working as intended for the current version of Material.

**Closed by asyncLiz** 2020-09-25 20:40 UTC
Labels: Focus Area: Components, Type: Feature

**Comment by lazylazyllama** [comment] 2020-09-25 23:56
> This is because the web, unlike native, maintains focus on an element after clicking on it and does not remove focus until another element is clicked on.

I don't agree here, as this just a historic issue of the web, which is why `focus-visible` was introduced in the first place.

**Comment by lazylazyllama** [comment] 2021-02-26 03:38
@asyncLiz As you can see here: https://www.chromestatus.com/feature/5658873031557120 even the default behaviour of how the web is doing it seems to be changing now
