### ISSUE TITLE
Generated decorator helper causes build failure in rollup

### ISSUE THREAD

**Issue by samuelli** [material-components/material-components-web-components#323] opened 2019-07-30 18:58 UTC
Repro steps:
 * Import an element: `import '@material/mwc-tab-bar'`
 * Build using rollup

Actual:
 * Build failure:
```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
node_modules/@material/mwc-tab-bar/mwc-tab-bar.js
11: }
12: 
13: var __decorate = this && this.__decorate || function (decorators, target, key, desc) {
                     ^
14:   var c = arguments.length,
15:       r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc,
...and 1 other occurrence
```
because the generated decorator helper references `this`. `this` in ES modules is `undefined`.

Expected: can easily build in rollup and/or documented workarounds.

A potential workaround is to redefine `this` in your rollup configuration.
```
...
moduleContext: {
    [require.resolve('@material/mwc-tab-bar')]: 'window',
}
```

**Comment by aomarks** [comment] 2019-07-30 19:02
We should set `importHelpers: true` and add a dependency on `tslib` so that the helpers like `__decorate` are imported from that module instead of inlined. This should also help code size and performance, since currently every element has its own duplicate of `__decorate` (and maybe some other helpers), not to mention most typescript users are also going to need this function too.

(This is arguably also a tsc bug, in that when emitting a module, `this` and `var` aren't going to set globals, so not only is there a copy of each helper at every call site, there is no runtime de-duplication via globals.)

**Comment by aomarks** [comment] 2019-08-14 20:37
Closing as dupe of https://github.com/material-components/material-components-web-components/issues/257

**Closed by aomarks** 2019-08-14 20:37 UTC
Labels: Priority: High, Source: Hooli, Type: Bug
