### ISSUE TITLE
Question about direction of form inputs and validation/styling [question]

### ISSUE THREAD

**Issue by silenceisgolden** [material-components/material-components-web-components#100] opened 2018-08-23 17:19 UTC
From my understanding, there are limitations on having a `<form>` element be in a different shadow root than the input element children:

pseudo example

```
<element>.shadowRoot
  <form>
    <element>.shadowRoot
      <input>
```

I am wondering about the direction of the form elements that are nested in the inner shadow DOMs with regard to:

1. how form validation is intended to work
2. form element custom styling before Shadow Parts are available
3. how this would gracefully degrade in a non-JS environment

Thanks for any insight you all can share this early, and my email is public on my GitHub profile for a closed discussion if necessary and able.

**Comment by azakus** [comment] 2019-07-12 21:54
Duplicate of #289

**Closed by azakus** 2019-07-12 21:54 UTC
Labels: Type: Question
