### ISSUE TITLE
<mwc-icon-button> should support SVG and images

### ISSUE THREAD

**Issue by aomarks** [material-components/material-components-web-components#343] opened 2019-08-02 19:22 UTC
The MDC icon button supports specifying your icon as a ligature, an `<svg>`, or an `<img>`: https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button#icon-button-toggle-with-svg

`<mwc-icon-button>` currently only supports the Material Icons ligature style. I imagine SVGs would be the most common way users will want to provide custom icons.

Also, is it currently possible to set a font other than Material Icons, if users want to implement their own ligatures in a custom font?

**Comment by fernandopasik** [comment] 2019-08-06 20:02
should this one be implemented with `<slot></slot>`?

**Comment by fernandopasik** [comment] 2019-08-06 20:04
This one might be duplicate of #156

**Comment by azakus** [comment] 2019-08-10 00:19
Duplicate of #156

**Closed by azakus** 2019-08-10 00:19 UTC
Labels: Type: Enhancement
