### ISSUE TITLE
[Bug] Slider's track container background is not updated by --mdc-theme-secondary

### ISSUE THREAD

**Issue by kkimdev** [material-components/material-components-web-components#80] opened 2018-07-22 00:39 UTC
For example, with `--mdc-theme-secondary: black;` It results:

![image](https://user-images.githubusercontent.com/503414/43041134-e4340b4a-8d0b-11e8-8b0c-14fe7e18d08d.png)

Notice that the right side track container background is still green-ish.

This is because slider's scss is compiled to a constant color for that background.  Ideally it should be compiled to css that reflects `--mdc-theme-secondary` variable. https://github.com/material-components/material-components-web/blob/bfdd2ddce0e20187342224282c6b625008e7f074/packages/mdc-slider/_mixins.scss#L105

Other places correctly takes account `--mdc-theme-secondary` but not on that line, and I suspect it's due to the use of `rgba(...)` function there.

Either it shouldn't compile to a constant color, or provide a way to use user compiled scss with their choice of variables for slider material component.

**Comment by kkimdev** [comment] 2018-07-22 00:40
@acdvorak

**Comment by svencowart** [comment] 2019-09-25 15:01
I spent some time troubleshooting this bug and here is what I have found:

The [mdc-slider-rail-color_ mixin](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/_mixins.scss#L434) uses the [mdc-theme-prop-value](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_variables.scss#L131) function.  _mdc-theme-prop-value_ does not utilize css variables but instead uses constant sass variables.

I suspect that a part of the issue is the rgba function requires an rgb value and cannot accept hex values.  If you look at the [mdc-theme-prop](https://github.com/material-components/material-components-web/blob/master/packages/mdc-theme/_mixins.scss#L70) mixin, there is special handling for using css variables which is why it works in other places.  However, because rgba requires an rgb value this does not work here.  The implementation of _mdc-theme-prop-value_ needs to change in order to fix this bug.  When I find additional time, I will try to come up with a possible solution and report back.

**Comment by svencowart** [comment] 2019-09-26 18:40
I have submitted a fix within material-components-web:  https://github.com/material-components/material-components-web/pull/5132

**Comment by asyncLiz** [comment] 2020-01-17 00:29
@svencowart does the change to MDC automatically fix this issue?

**Comment by svencowart** [comment] 2020-01-20 21:36
@async Yes, it does.  This issue can be closed.

**Comment by asyncLiz** [comment] 2020-03-09 22:02
Verified and closing as fixed

**Closed by asyncLiz** 2020-03-09 22:02 UTC
Labels: Area: Styling, Component: Slider, Type: Bug
