### ISSUE TITLE
All MWC crash in Safari 14

### ISSUE THREAD

**Issue by herberthobregon** [material-components/material-components-web-components#1850] opened 2020-09-29 14:30 UTC
**Describe the bug**

**To Reproduce**
1. Open Safari, go to https://material-components.github.io/material-components-web-components/demos/checkbox/
2. Click on checkbox, and safari crash

**Expected behavior**
work

**Screenshots**
![image](https://user-images.githubusercontent.com/6503845/94572236-06c11380-022e-11eb-8487-04dda98a166a.png)

**Browser Version (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14

**Comment by asyncLiz** [comment] 2020-09-29 19:02
This is a duplicate of https://github.com/material-components/material-components-web-components/issues/1720. Unfortunately this is a bug with WebKit in Safari 14 on Desktop. We've notified Apple of the production regression.

**Closed by asyncLiz** 2020-09-29 19:02 UTC
Labels: Focus Area: Components, Type: Bug
