### ISSUE TITLE
mwc-select Theme Option (--mdc-select-ink-color) not working

### ISSUE THREAD

**Issue by syedabuthahirm** [material-components/material-components-web-components#885] opened 2020-02-19 06:32 UTC
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Windows 10

**Current behavior:**
--mdc-select-ink-color doesn't work

**Expected behavior:**
When We select a item the input value shout adopt (--mdc-select-ink-color) value color as mentioned in doc

**Related code:**

```css
mwc-select {
  --mdc-select-ink-color: red;
}
```

**Comment by e111077** [comment] 2020-02-19 11:18
Duplicate of #869

**Closed by e111077** 2020-02-19 11:18 UTC
