### ISSUE TITLE
Clicking on certain components crashes the browser tab in Safari 14

### ISSUE THREAD

**Issue by stephenwade** [material-components/material-components-web-components#1895] opened 2020-10-11 19:32 UTC
**Describe the bug**
Whenever I click on certain MWC components in Safari, the browser tab crashes. (It reloads and a message appears at the top saying "This webpage was reloaded because a problem occured.")

I ran into this problem when working on a personal project, but I can also reproduce it on [the MWC demo Glitch app](https://mwc-demos.glitch.me/).

The problem happens when I click any of the following components:
- `<mwc-button>`
- `<mwc-checkbox>`
- `<mwc-radio>`
- `<mwc-switch>` (including the disabled ones)
- `<mwc-tab-bar>` / `<mwc-tab>`
- `<mwc-textarea>`
- `<mwc-textfield>`

It does not happen if I click on any of the following components:
- `<mwc-formfield>` (which triggers the associated `<mwc-checkbox>`, `<mwc-radio>`, or `<mwc-switch>`)
- `<mwc-icon-button>`
- `<mwc-icon-button-toggle>`
- `<mwc-list>` / `<mwc-list-item>`

**To reproduce**
1. Go to https://mwc-demos.glitch.me/.
2. Click on any of the problem components.
3. The browser tab crashes.

**Expected behavior**
The browser tab does not crash.

**Screenshots**

**Browser version**
 - OS: macOS Catalina 10.15.7 (19H2)
 - Browser: Safari 14.0

**Additional context**
I have checked for updates for Safari and macOS and verified that I am running the latest version available of both. The issue does not happen in Chrome or Firefox. It also does not happen in mobile Safari on my iPhone 11 Pro (iOS 14.2, 18B5061e).

If you can't reproduce the issue, I'm happy to collect and provide more debugging information; I'm just not sure what exactly would be helpful. I will happily follow directions to collect whatever would be helpful to diagnose the issue.

**Comment by JosefJezek** [comment] 2020-10-15 12:29
duplicate of https://github.com/material-components/material-components-web-components/issues/1720

**Comment by taylor-vann** [comment] 2020-10-16 22:39
closing as duplicate #1720

**Closed by taylor-vann** 2020-10-16 22:39 UTC
Labels: Focus Area: Components, Type: Bug
