### ISSUE TITLE
Option to set mwc-top-app-bar-fixed less that width of window

### ISSUE THREAD

**Issue by johnthad** [material-components/material-components-web-components#527] opened 2019-10-02 02:35 UTC
**I'm submitting a:**
- [ ] bug report
- [x] feature request

**What OS are you using?**
all

**Current behavior:**
`mwc-top-app-bar-fixed` and `mwc-top-app-bar` are always the width of the window. As such they cannot replace the Polymer `app-toolbar` in many situations.

**Expected behavior:**
There should be a CSS custom property for changing the `mwc-top-app-bar-fixed` (and `mwc-top-app-bar`) with to a component that is not the width of the screen.

**Other information:**
The width of a Polymer `app-toolbar` can be limited to its parent component without resorting to an iframe.

**Comment by johnthad** [comment] 2019-10-02 14:25
In playing with DevTools, it seems that if I could set `position: unset` on the class `mdc-top-app-bar` of `mwc-top-app-bar-fixed`'s `<header>` element, I could achieve what I want, and dump Polymer `app-toolbar`

**Comment by doktordirk** [comment] 2019-10-27 17:11
as i see it, it's coming from a regression in https://github.com/material-components/material-components-web-components/commit/553e28332a0a97a2a3b2e8fd1df60cf4ee3249c4 where [here](https://github.com/material-components/material-components-web-components/blame/master/packages/top-app-bar/src/mwc-top-app-bar.scss#L22) `:host` changed from `display: inline-flex` to `display: block`. with `inline-flex` the app bar would only fill it's container and not the hole page. 
at the time of writing this is still visible https://material-components.github.io/material-components-web-components/demos/top-app-bar.html which still uses `inline-flex` there

**Comment by johnthad** [comment] 2019-11-06 21:27
> it.s achievable with setting scrollTarget to the desired container

Thanks for the reply. How would I do this? See https://stackblitz.com/edit/mwc-appbarfixed

I mostly copied one of the demos and assigned `content` to `scrollTarget` but the app bar still runs the width of the window.

**Comment by doktordirk** [comment] 2019-11-07 08:13
> > it.s achievable with setting scrollTarget to the desired container
> 
> Thanks for the reply. How would I do this? See https://stackblitz.com/edit/mwc-appbarfixed
> 
> I mostly copied one of the demos and assigned `content` to `scrollTarget` but the app bar still runs the width of the window.


<!-- 
from what i gathered one  missing part in the docs example is that an element with 'mdc-drawer-app-content' is needed for the drawer to set the right width . that one then also was my scroll target
--
  |   | <div
  |   | ref="appContent"
  |   | slot="appContent"
  |   | class='mdc-drawer-app-content app-content'
  |   | >

**Comment by johnthad** [comment] 2019-11-07 12:26
Sorry, I'm not following you. There is no slot named `appContent` in `mwc-top-app-bar` or `mwc-top-app-bar-fixed`. `scrollTarget` is a property|attribute that is the default slot.

In my inbox I see a comment from on Oct 27th that has been deleted:


>From:  doktordirk <notifications@github.com>
>Created at Sun, Oct 27, 2019 at 1:11 PM
>
> as i see it, it's coming from a regression in [553e283](https://github.com/material-components/material-components-web-components/commit/553e28332a0a97a2a3b2e8fd1df60cf4ee3249c4) where [here](here) :host changed from display: inline-flex to display: block. with inline-flex the app bar would only fill it's container and not the hole page.
> at the time of writing this is still visible [https://material-components.github.io/material-components-web-components/demos/top-app-bar.html](https://material-components.github.io/material-components-web-components/demos/top-app-bar.html) which still uses inline-flex there

Is this the problem? Was a bug created? If so this issue should be reclassified **bug** vs **feature**.

**Comment by azakus** [comment] 2019-11-07 22:46
Is there a particular reason you need the top-app-bar to be less than the width of the app?
It appears this is intended in the spec, but if you have a good use case, we can talk to the spec designers to try and fit this in.

**Comment by johnthad** [comment] 2019-11-08 02:25
I have master-detail cases where there two panels with different headers are side-by-side, such as image thumbnails on the left, and one full image on the right (similar to a PDF viewer). Another case is a catalog of folders and forms on the left, and other items to the right (the pull-out draw has the app's master menu). To get away from PolymerElements, I'm currently using a `div` for the toolbar with a scrolling `div` underneath. However separate `app-toolbar` are much easier to manage.

**Comment by govis** [comment] 2020-01-15 16:25
Also, to keep a mobile layout presentable in desktop setting one might want to set <code>max-width: x</code> on the container containing the <code>mwc-top-app-bar</code>. Currently the <code>mwc-top-app-bar</code> sticks out to the right

![image](https://user-images.githubusercontent.com/971651/72451288-b1b99c00-3789-11ea-82cc-572a929642ee.png)

**Comment by MarcSkovMadsen** [comment] 2020-04-10 09:32
I also need this.

I would like to enable my self and [Panel](https://panel.holoviz.org/) users to develop awesome apps in a Jupyter Notebook using Python.

Currently the `mwc-top-app-bar` looks like this

![image](https://user-images.githubusercontent.com/42288570/78916337-9e1e8880-7a8d-11ea-9561-6b87674667b5.png)

See also https://github.com/material-components/material-components-web-components/issues/1097

**Comment by MarcSkovMadsen** [comment] 2020-04-10 10:33
I tried the `scrollTarget` option. But it does not work fully.

I've created a seperate issue on this https://github.com/material-components/material-components-web-components/issues/1106

![image](https://user-images.githubusercontent.com/42288570/78984613-fd7ca700-7b26-11ea-8193-ed5cec7084fd.png)

**Comment by MarcSkovMadsen** [comment] 2020-04-10 15:48
For the record I managed find the the problem in https://github.com/material-components/material-components-web-components/issues/1106 and fix it.

**Comment by e111077** [comment] 2020-07-09 19:40
fixed in #1508

**Closed by e111077** 2020-07-09 19:40 UTC
Labels: Component: Top App Bar, Focus Area: Components, Spec Question, Styling, Type: Feature

**Comment by derolf** [comment] 2021-12-03 12:25
Set `max-width: inherit;` on the `header` element.
