### ISSUE TITLE
Slider min/max set incorrect if min is over 100

### ISSUE THREAD

**Issue by rowanc1** [material-components/material-components-web-components#1087] opened 2020-04-08 15:29 UTC
**Describe the bug**
When setting min and max at the **same time** the slider breaks if min is greater than 100 (or probably the last valid min?).

Pretty sure something is going on here:
https://github.com/material-components/material-components-web-components/pull/1081/files#r405600964

I don't think that it is the same as this:
#2269

This is only the case if both min/max are set at the same time.

**To Reproduce**
Install @material/mwc-slider@0.14.1

This works:
`<mwc-slider pin min="99" max="2000" step="10"></mwc-slider>`
And then in JS: `$0.min = 101`.

This doesn't:
`<mwc-slider pin min="101" max="2000" step="10"></mwc-slider>`

**Expected behavior**
The min/max range should work and not be replaced by the initial defaults.
Update including min > 100 should work!

**Screenshots**

I am using this to update the min and max, which works only when the min is < 100

Expected:
![sliders](https://user-images.githubusercontent.com/913249/78801194-95d52900-7979-11ea-94f1-89153b16c7ad.gif)

When the range is over 100:
![broken-slider](https://user-images.githubusercontent.com/913249/78801527-0ed48080-797a-11ea-9218-636f7ab21a85.gif)

**Browser Version (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version @material/mwc-slider@0.14.1

**Comment by rowanc1** [comment] 2020-04-08 15:40
Looking into this further, likely that #1081 actually fixes this and maybe hasn't been released yet?

**Comment by e111077** [comment] 2020-04-08 21:27
fixed in #1081 duplicate of #1079. Please try this out with npm canary release `@material/mwc-slider@canary` If you are still having issues with this, please comment and I will reopen

**Closed by e111077** 2020-04-08 21:27 UTC
Labels: Component: Slider, Focus Area: Components, Type: Bug
