### ISSUE TITLE
[MWCSelect] Width Control is Buggy

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1818] opened 2020-09-15 18:31 UTC
**Describe the bug**
It appears that a bug exists when setting an arbitrary `width` to a `mwc-select` component, if `outlined`, the outline boundaries will not respect the set width and if `filled` the fill boundaries will behave the same way - not respecting the `width`.

**To Reproduce**
```js
<div class="flexbox" slot="actionItems">
              <hr />
              <!-- action icons -->
              <mwc-select outlined>
                <mwc-list-item
                  graphic="icon"
                  value="en"
                  selected
                  >English</mwc-list-item
                >
                <mwc-list-item graphic="icon" value="fr"
                  >French</mwc-list-item
                >
                <mwc-list-item graphic="icon" value="ar"
                  >Arabic</mwc-list-item
                >
              </mwc-select>
              <hr />
              <dark-mode-toggle
                appearance="toggle"
                permanent
              ></dark-mode-toggle>
            </div>
```

```css
mwc-select {
        width: 156px;
        padding: 0 6px;
        /* --mdc-list-side-padding: 8px; */
        /* inherits the styles of mwc-menu internally */
        --mdc-menu-item-height: 32px;
        /* --mdc-theme-surface: aliceblue; */
        /* inherits the styles of mwc-list internally */
        --mdc-list-vertical-padding: 0px;
        /* --mdc-list-side-padding: 30px; */
      }
.flexbox {
        display: flex;
        align-items: center;
      }
```

**Screenshots**
- `outlined` variant:
![image](https://user-images.githubusercontent.com/11601622/93249930-f3bc3700-f789-11ea-8911-2321016e1cee.png)

- `filled` variant:
![image](https://user-images.githubusercontent.com/11601622/93250017-13ebf600-f78a-11ea-8e06-dbce93a97c4a.png)

**Comment by taylor-vann** [comment] 2020-09-19 00:23
Hey @aress31!

Thanks for reaching out.

Before we move forward, if you could please provide the following to help us help you:
- A JSBin to highlight the featured bug.
- A little more explanation alongside your screenshots (maybe examples of intended behavior as well).

**Comment by aress31** [comment] 2020-09-19 20:32
Hi @taylor-vann 

Thanks for the answer, I pasted the relevant code and style in my previous message, if you have a MWC pre-configured template I could use on `JSBin` or another platform please feel free to share. 

The intended behaviour is to reduce the `width` of the `mwc-select` so that it does not take up more space than needed in the bar. So the goal is for me to control the `width` of `mwc-select`.

Best regards,
Alex

**Comment by asyncLiz** [comment] 2020-09-21 19:13
I was able to reproduce this bug with https://jsbin.com/yotijoyapa/edit?html,output

The problem is the [min-width](https://github.com/material-components/material-components-web/blob/8d5b84fb260506c69fa93246aee538db89db8fc3/packages/mdc-select/_select.scss#L123) set on the inner `.mdc-select` of `200px`, which the user cannot override from outside the shadow root. Setting a width of less than `200px` causes the bug to appear.

This should be fixed in #1829

**Comment by aress31** [comment] 2020-09-21 19:45
Happy to hear the bug has been fixed, thanks @asyncLiz !

**Comment by allan-chen** [comment] 2020-09-21 20:14
Will close when PR is merged

**Comment by aress31** [comment] 2020-09-22 00:10
@allan-chen and @asyncLiz I just noticed that the `height` behave the same way than the width. Please see:

![image](https://user-images.githubusercontent.com/11601622/93833384-5cb31b80-fc70-11ea-90d9-83f97dcd3644.png)

Could it be possible to fix this bug as well?

**Comment by allan-chen** [comment] 2020-09-22 00:13
As mentioned in #1810, height is part of the density epic, which is tracked in #841.

**Comment by aress31** [comment] 2020-09-22 00:15
Yeah but it is still a property that can currently have an effect on the look of the `mwc-select` (in a buggy way).

**Comment by allan-chen** [comment] 2020-09-22 00:19
We will first need to establish how to introduce the density subsystem from the upstream MDC library into all relevant component in this library using #841 for tracking. We'll update that issue with progress & begin implementation on the components (including select, textfield etc.) once an implementation strategy has been defined.

**Comment by aress31** [comment] 2020-09-22 00:23
Got it thanks for the feedback @allan-chen

**Comment by allan-chen** [comment] 2020-09-29 17:05
Issue has been resolved [upstream](https://github.com/material-components/material-components-web/pull/6503)

**Closed by allan-chen** 2020-09-29 17:05 UTC
Labels: Component: Select, Focus Area: Components, Severity: Medium, Type: Bug, Why: improve ergonomics
