### ISSUE TITLE
Add the new elements (from CHANGELOG.md) to the demo page

### ISSUE THREAD

**Issue by kenchris** [material-components/material-components-web-components#426] opened 2019-08-27 10:35 UTC
New elements like mwc-textfield are not there, and I believe that all shipped elements should be show-cased

**Comment by aomarks** [comment] 2019-10-01 18:45
Closing as dupe of https://github.com/material-components/material-components-web-components/issues/433. We need to fix the build process and re-deploy the site.

**Closed by aomarks** 2019-10-01 18:45 UTC
Labels: Area: Docs, Component: Text Field
