### ISSUE TITLE
Unable to modify the height of the mwc-textfield

### ISSUE THREAD

**Issue by rajashekar9** [material-components/material-components-web-components#975] opened 2020-03-06 06:47 UTC
I am using mwc-textfield in lit-element(2.2.1). The problem is I want to modify the height of the mwc-textfield. I have gone through the official documentation of the mwc-textfield. I found that there is a SASS mixin to modify the height of it. I tried to apply sass mixin but, it didn't work. I think the syntax is wrong. Any help would be appreciated.

**Comment by asyncLiz** [comment] 2020-03-06 15:25
It is not possible to use sass mixins with Material Web Components. Changing textfield's height will be achievable with the density system in #841.

**Comment by asyncLiz** [comment] 2020-03-06 15:25
Closing as duplicate of #654

**Closed by asyncLiz** 2020-03-06 15:25 UTC
