### ISSUE TITLE
mwc-slider drag gets stuck

### ISSUE THREAD

**Issue by cannoneyed** [material-components/material-components-web-components#1279] opened 2020-05-07 21:38 UTC
**Describe the bug**
When releasing the mouse outside of container element, the mwc-slider doesn't cancel it's drag mousemove handling and keeps moving the slider when the mouse is moved back into the container element. The container element is itself a litElement web component so it might have something to do with the mouse event being handled outside of the container's shadow DOM?

**To Reproduce**
1. Begin dragging slider
1. Drag outside of the parent component's boundaries (to the left or right only, vertically is fine)
1. Release the mouse
1. Move the mouse back into the parent component and observe the slider still moving

**Expected behavior**
I expect the mousemove handler to be immediately cancelled when the user mouseup event happens.

**Screenshots**
![2020-05-07 14 37 57](https://user-images.githubusercontent.com/7818584/81347137-63017c00-9070-11ea-93af-c85a53ad2cfe.gif)
(Releasing the mouse outside of the container, then moving it back in)

**Browser Version (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Latest

**Comment by asyncLiz** [comment] 2020-05-08 21:34
I was trying to reproduce this, and I was only able to reproduce it by moving the mouse outside the window's context.

That means moving it entirely outside of the browser, or outside an `<iframe>` if that's involved (such as the case with jsbin).

https://jsbin.com/befasasuhe/edit?html,output

I can't reproduce if I move to the left/right and release outside of the bordered section but _within_ the iframe context. If I move to the right outside of Chrome's window, the bug occurs. If I move to the left outside of the iframe context into jsbin's code section, the bug also occurs.

Can you confirm this is the case in your situation? Are you using iframes? If not, can you upload a reproduction showing the problem that does not involve iframes?

**Comment by cannoneyed** [comment] 2020-05-09 01:26
Nope, not in an iframe - in a lit-element web component. When the mouse is moved outside of the root web component, the behavior happens (the app is built of web components inside other web components).

Hope this helps, I can share a working demo with you next week.

**Comment by ernsheong** [comment] 2020-05-17 03:24
I am also seeing this behavior in a Shadow DOM, when cursor leaves the element while dragging, this happens.

**Comment by ernsheong** [comment] 2020-05-17 12:41
Here's a link to a Storybook that demonstrates the problem. https://ui.beliantech.com/?path=/story/bt-components--bt-slider

Not sure if it is something that mwc can fix. Thanks a lot in advance

**Comment by e111077** [comment] 2020-05-18 21:30
Heya sorry this was fixed upstream a few commits ago. Please try on Canary. Will reopen if it is still an issue in Canary

**Comment by e111077** [comment] 2020-05-18 21:31
note: currently the demos on our github pages is running on canary

https://material-components.github.io/material-components-web-components/demos/slider/

**Comment by noelklein** [comment] 2021-06-29 16:42
@e111077 this is still an issue. I'm on a macbook with Chrome and can reproduce it on your demo page. When I click on the slider thumb, hold the mouse button, then move the cursor outside of the window and release the mouse button, then it keeps moving the thumb around when moving the cursor back into the window.

**Comment by e111077** [comment] 2021-06-29 20:38
Hmm it seems upstream we never actually pointer capture despite checking whether it's iOS or not (since iOS has a bad implementation of pointer capture). This seems like an upstream issue on material-components/material-components-web

**Comment by e111077** [comment] 2021-06-29 23:04
Can't check whether pointerup is initiated from outside the window. Best we can do is:

1. stop dragging altogether if drag leaves window
2. stop dragging if user clicks off of window

**Comment by e111077** [comment] 2021-06-29 23:18
I filed an issue upstream as it's still an issue with the latest version of M2 slider: https://github.com/material-components/material-components-web/issues/7209

**Comment by e111077** [comment] 2021-07-14 23:12
checked, our repro was broken. M2 slider does not have this issue. Working on releasing the M2 slider right now.

**Comment by noelklein** [comment] 2021-07-15 14:19
@e111077 when can we expect a new npm package version to be available?

**Comment by e111077** [comment] 2021-07-16 17:54
within the next few weeks or so. It's working just fine, but test coverage and theming is not there yet.

**Comment by noelklein** [comment] 2021-07-16 18:30
@e111077 Is it possible to get a pre-release or canary? How can I help? I'm happy to provide unit tests. Not sure how I could help with theming.

**Comment by e111077** [comment] 2021-07-16 18:34
I might be able to ship to canary without tests due to it being a blocker for form submission integration work, but unfortunately the theming is not parallelizable since it's coming straight from the design team

**Comment by noelklein** [comment] 2021-07-23 14:31
@e111077 any chance we could get that canary released?

**Comment by e111077** [comment] 2021-07-23 18:15
bot auto-releases canary upon commit to main. #2567 is awaiting material-components/material-components-web#7256

**Closed** 2021-07-26 21:21 UTC
Labels: Feedback Requested, Focus Area: Components, Type: Bug
