### ISSUE TITLE
Extra line below the input, which is visible sometimes

### ISSUE THREAD

**Issue by rutwick-alic** [material-components/material-components-web-components#2082] opened 2021-01-19 11:38 UTC
The error is simple. A second border, equal to the width of the error message placeholder shows up when you focus in the text input. That's very likely the border for the error message itself. Is there way to remove it, or only show when the error is shown?

UPDATE: I figured out it is for the helper text. But I don't have a helper text, I don't need that border.

![underline](https://user-images.githubusercontent.com/72026410/105029864-ec2ed680-5a78-11eb-98f3-c4b4c09aae98.jpg)

**Comment by asyncLiz** [comment] 2021-01-19 18:15
Text field cheerleader here! Can you paste your DOM structure and what browser you're seeing this in?

You mention you don't have helper text, so there should not be a `<div class="mdc-text-field-helper-line">` element if there is one. An empty helper line may be causing visual artifacts.

**Comment by rutwick-alic** [comment] 2021-01-19 18:47
Hey, thanks a lot @asyncLiz . Sure, here is the DOM. I am seeing this in Chrome (87).

                    ```
<mwc-textfield
                        id="appl-age"
                        class="numeric-input"
                        label="Enter Age"
                        type="number"
                        defaultValue="18"
                        onInput={(e) => this.handleAgeChange(e) }
                        min="18"
                        max="35"
                        validationMessage="Please enter a value between 18 and 35"
                        autofocus
                    ></mwc-textfield>
```

I have been seeing this for all my input fields, in another application. It appears when you focus in them. An important point is that this doesn't happen every time.

**Comment by asyncLiz** [comment] 2021-01-19 18:58
Is there any consistent amount of time you can reproduce it? Do you see the artifact here? https://jsbin.com/robujukiwo/edit?html,output

Can you give us more information about your system OS and version, as well as whether or not your OS or Chrome has any zoom level or resolution scaling applied?

**Comment by rutwick-alic** [comment] 2021-01-19 19:02
Hey, I don't see it in your snippet. I must tell you that we pass the min/max values as props, and manipulate the error message via a function.

My OS is Win 10. No zoom, however I test the component in the mobile mode (via Chrome console).

**Comment by rutwick-alic** [comment] 2021-01-19 19:05
My bad, I had to apply a width to the snippets output, and yes, I do see the underline!

![underline](https://user-images.githubusercontent.com/72026410/105080800-5b2b2000-5ab7-11eb-85db-1c5adeaca9da.jpg)

**Comment by asyncLiz** [comment] 2021-01-19 19:15
Unfortunately I still cannot reproduce on a Windows 10 machine while following your steps.

I've seen a similar visual artifact from our internal screenshot tests in Chrome's emulated mobile rendering, and I'm suspicious of the fuzziness of the bottom line border. It should be much sharper (compare it to the gray border between the style sections of your screenshot, which indicates it's not a monitor/resolution/screenshot issue).

Are you only seeing this artifact in the Chrome mobile debugger tool?

**Comment by rutwick-alic** [comment] 2021-01-20 05:28
The fuzziness is due to the screenshot being cropped in Paint, the line is much clearer and sharper irl and you can even see it appear. By the way now that you mentioned it, I checked the issue in the normal desktop mode and then the mobile mode, it happens in Chrome's emulated mobile mode, for sure.

**Comment by dfreedm** [comment] 2021-01-23 02:00
Chrome's emulated mobile mode is probably applying a magnification setting that isn't a round number, so this may only exist in that mode and not on a real device.

I'm closing this for now, but if you can demonstrate this issue on a real device, I'll be happy to reopen it.

**Closed by dfreedm** 2021-01-23 02:00 UTC
Labels: Feedback Requested, Focus Area: Components, Type: Bug
