### ISSUE TITLE
[mwc-select] doesn't show the list items on disabled toggle

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#2272] opened 2021-03-20 15:31 UTC
**Describe the bug**
When setting `disabled` to `true` on `mwc-select` and setting it back to `false`, the list doesn't show up anymore. 

**To Reproduce**
https://jsbin.com/jemefur/edit?html,output

version 0.20.0

Edit: I just realized the problem only occurs when `mwc-select` is initialized with `disabled` set to `true`. If the attribute `disabled` on the element is omitted initially there is no problem if we toggle the value (see updated jsbin)

**Comment by asyncLiz** [comment] 2021-04-05 21:07
Thanks for the bug! Looks like the problem is an [early return case](https://github.com/material-components/material-components-web-components/blob/583644a66f0a3717609a426798bf846fbf8365bf/packages/select/mwc-select-base.ts#L710), we should be able to fix this quickly.

**Comment by asyncLiz** [comment] 2021-04-09 19:48
Should be fixed now

**Closed by asyncLiz** 2021-04-09 19:48 UTC
Labels: Component: Select, Focus Area: Components, Type: Bug
