### ISSUE TITLE
"mwc-ripple" has already been used with this registry 

### ISSUE THREAD

**Issue by jayhamilton** [material-components/material-components-web-components#1940] opened 2020-11-06 04:01 UTC
I have an interesting use case. We are importing web components that include mdc components in one php page and web components that include mwc components (0.18.0) in another php page. Our web components are written using StencilJs. When we switch from one page to another we get the following error:

`DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-ripple" has already been used with this registry`

I saw another issue with the same error get resolved in the latest version. That scenario involved the user of unpkg/cdn. We don't use that. We build the StencilJs web components and then take the resulting javascript and import the components directly in the page.

**Comment by darktears** [comment] 2020-11-06 18:10
I can reproduce the issue over here. The code that triggers it is the following:

`import '@material/mwc-button';
import '@material/mwc-icon-button';`

If I use one or the other it works just fine (of course my application breaks).

**Comment by jayhamilton** [comment] 2020-11-06 20:25
@darktears are you seeing that with the 0.19.1?

**Comment by darktears** [comment] 2020-11-06 20:27
Yes, it works fine if I downgrade to 0.18

Code is located here: https://github.com/foldable-devices/demos/tree/master/battleship

Just bump the version in package.json.

**Comment by jayhamilton** [comment] 2020-11-06 20:30
Hmm, my problem is with version 0.18.0

**Comment by n1ywb** [comment] 2020-11-08 15:32
may be related to https://github.com/material-components/material-components-web-components/issues/1675 

and

https://github.com/material-components/material-components-web-components/pull/1678

**Comment by n1ywb** [comment] 2020-11-09 01:00
here's an ugly hack that works around the problem by monkey patching window.customElement.define and guarding against defining mwc-ripple twice

```
      const _define = window.customElements.define.bind(window.customElements)
      let rippleDefined = false;
      window.customElements.define = ((tagName, klass) => {
        console.log('define custom element', tagName, klass)
        if (tagName == 'mwc-ripple') { 
          if (rippleDefined) {
            return 
          }
          else {
            rippleDefined = true;
          }
        }
        return _define(tagName, klass)
      }).bind(window.customElements)
    })()
```

**Comment by jayhamilton** [comment] 2020-11-09 03:43
@n1ywb yeah it seems like there are a number of related issues in this area. Thanks for the hack. Will give it a try.

**Comment by n1ywb** [comment] 2020-11-09 14:40
I made a simpler hack that just turns definition errors into warnings (after I had the same problem with another element)

```
<head>
  <script>
    (()=>{
      const _define = window.customElements.define.bind(window.customElements)
      window.customElements.define = ((tagName, klass) => {
        try {
          return _define(tagName, klass)
        }
        catch (err) {
          console.warn(err)
        }
      }).bind(window.customElements)
    })()
  </script>
</head>
```

**Comment by taylor-vann** [comment] 2020-11-13 23:31
Hey @jayhamilton

This usually happens when there are conflicting versions of our components in the same build. Hence the the failure to define a new component in `CustomElementRegistry `.

From your description alone, I might double check to confirm there aren't duplicate versions of material in your build.

But If you could provide us with examples, a little code, or your setup we might be able to help you further! :)

**Comment by jayhamilton** [comment] 2020-11-13 23:39
Thanks Taylor. I will put something together this weekend. However, the issue simply is that we use Stencil JS to create web components. We just began to embed material web components (mwc) and material components web (mdc) into some of them. We have php pages that load various web components we produce.

**Comment by taylor-vann** [comment] 2020-11-14 00:14
Very cool @jayhamilton, glad to hear about your team's webcomponent efforts!

The scenario you just described has the potential to cause a few naming conflicts. I'm also not exactly an expert in Stencil JS :)

But please keep us up to date on your progress! I'm sure others might have a similar background and could benefit from what you find :)

Talk soon!

**Comment by jayhamilton** [comment] 2020-11-16 03:27
I have two Stencil web components that are included in an html page. The are imported separately as esm modules.
`<script type="module" src="modulea.esm.js"></script>
  <script type="module" src="moduleb.esm.js"></script>`

modulea has the following import within its jsx template (Stencil uses JSX): 
 `import "@material/mwc-button";
  import "@material/mwc-textfield";
  import "@material/mwc-select";
  import "@material/mwc-list/mwc-list-item";` 

this component's package.json has the following dependencies: 
` "dependencies": {
    "@material/mwc-button": "^0.18.0",
    "@material/mwc-list": "^0.18.0",
    "@material/mwc-select": "^0.18.0",
    "@material/mwc-textfield": "^0.18.0",
    "@material/theme": "^7.0.0"
  }`

moduleb uses the following imports 

`import "@material/mwc-list/mwc-list-item";
import "@material/mwc-list/mwc-list";
import "@material/mwc-textfield";`

however I just realized that the package.json did not have the mwc-list and mwc-textfield dependencies.  This condition produced the "mwc-ripple" error. 

I updated package.json for the second component to use the same version of mwc-list and mwc-textfield used by the first component and the mwc-ripple error no longer appears.  I now have a new error that I will need to investigate.

**Comment by dfreedm** [comment] 2020-11-20 23:37
Thanks for the analysis. Since you resolved your multiple versions issue, I'll close this issue. Thanks!

**Closed by dfreedm** 2020-11-20 23:37 UTC

**Comment by hata6502** [comment] 2021-09-05 09:00
```js
const define = window.customElements.define.bind(window.customElements)

customElements.define = (name, constructor, options) => {
  if (customElements.get(name)) {
    console.warn(`The definition of "${name}" was skipped because it has already been defined.`);

    return;
  }

  define(name, constructor, options);
};
```

**Comment by darktears** [comment] 2021-12-13 16:52
@dfreedm With 0.25.3 this error is still very much an issue. I have no special complicated project. I just use snowpack and a single JS module and the error still manifest if I use two components with the ripple dependencies in them for e.g. : 

```import '@material/mwc-button';```
```import '@material/mwc-icon-button';```

in the same file.
