### ISSUE TITLE
(feature) Material drawer component as web component

### ISSUE THREAD

**Issue by hastebrot** [material-components/material-components-web-components#27] opened 2018-05-11 19:10 UTC
Implementation in `material-components-web`:

https://github.com/material-components/material-components-web/tree/v0.35.1/packages/mdc-drawer

Material component page:

https://material.io/develop/web/components/drawers/

**Comment by frankiefu** [comment] 2019-02-22 23:12
Duplicate of https://github.com/material-components/material-components-web-components/issues/94

**Closed by frankiefu** 2019-02-22 23:12 UTC
Labels: Type: Enhancement
