### ISSUE TITLE
Errors in VS Code when trying to extend components

### ISSUE THREAD

**Issue by Misiu** [material-components/material-components-web-components#1708] opened 2020-08-18 09:45 UTC
**Describe the bug**
When trying to extend TextField and applying custom css properties I'm getting this error:

```
Class static side 'typeof HaTextField' incorrectly extends base class static side 'typeof TextField'.
  Types of property 'styles' are incompatible.
    Type 'CSSResult[]' is missing the following properties from type 'CSSResult': cssText, styleSheetts(2417)
```

**To Reproduce**
```
import { TextField } from "@material/mwc-textfield";
import { customElement, css, CSSResult } from "lit-element";

@customElement("ha-textfield")
export class HaTextField extends TextField {
  static styles: CSSResult[] = [
    TextField.styles,
    css`
      :host {
        --mdc-text-field-fill-color: var(
          --ha-card-background,
          var(--card-background-color, white)
        );
        display: block;
      }
    `,
  ];
}

declare global {
  interface HTMLElementTagNameMap {
    "ha-textfield": HaTextField;
  }
}
```

**Expected behavior**
VS Code shouldn't show any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1741838/90497469-6a442580-e147-11ea-89fc-a0345c1875d6.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - VS Code 1.48.0
 - eslint-plugin-lit: "^1.2.0", 

**Additional context**
I'm trying to add this to https://github.com/home-assistant/frontend.

**Comment by asyncLiz** [comment] 2020-08-18 18:08
This is a duplicate of https://github.com/material-components/material-components-web-components/issues/322.

Instead of extending the defined element class which registers the element, extend the base class:

```ts
import {TextFieldBase} from '@material/mwc-textfield/mwc-textfield-base';
import {style as TextFieldStyles} from '@material/mwc-textfield/mwc-textfield-css';

@customElement("ha-textfield")
export class HaTextField extends TextFieldBase {
  static styles: CSSResult[] = [
    TextFieldStyles,
    css`
      :host {
        --mdc-text-field-fill-color: var(
          --ha-card-background,
          var(--card-background-color, white)
        );
        display: block;
      }
    `,
  ];
}
```

Let us know if you have any questions!

**Comment by Misiu** [comment] 2020-08-19 11:40
@asyncLiz the error is gone.
Thank you for your quick reply!

**Closed** 2020-08-19 16:43 UTC
Labels: Feedback Requested, Focus Area: Components, Type: Bug
