### ISSUE TITLE
mwc-drawer: MDCDrawer:opened event fires twice

### ISSUE THREAD

**Issue by frankiefu** [material-components/material-components-web-components#220] opened 2019-02-07 20:35 UTC
I added an event listener to mdc-drawer, e.g.
```
drawer.addEventListener('MDCDrawer:opened', (e) => {
  console.log('MDCDrawer:opened');
});
```

And when the drawer is opened `MDCDrawer:opened` is logged 2 times in the console.

**Comment by straversi** [comment] 2019-02-19 20:29
It appears this was fixed by 9d51cc2224a1d0820944114ed3c54350ceba05f0, so thank you!

**Closed by straversi** 2019-02-19 20:29 UTC
Labels: Type: Bug

**Comment by frankiefu** [comment] 2019-02-21 18:19
Nice. Yeah verified it's fixed.

**Comment by guther** [comment] 2021-09-07 19:33
Here, the problem is still happened. I'm using "@material/drawer": "^12.0.0"
