### ISSUE TITLE
Styling request: mwc-drawer aside background color

### ISSUE THREAD

**Issue by motiejunas** [material-components/material-components-web-components#1324] opened 2020-05-18 07:43 UTC
**Is your feature request related to a problem? Please describe.**
I would like to override background color for `mwc-drawer` > `aside` as the hard-coded white color does not look nice with the dark theme.

**Describe the solution you'd like**
I wish I could override the color with a theme variable.

**Describe alternatives you've considered**
Considered to write a similar component by myself.

**Comment by asyncLiz** [comment] 2020-05-18 17:24
This can be fixed by removing [`prop-value()`](https://github.com/material-components/material-components-web/blob/18c04d069611b8cb92a651d91998dd882fc5c54f/packages/mdc-drawer/_variables.scss#L26-L31) from many of the variables in MDC.

**Comment by asyncLiz** [comment] 2020-05-19 02:21
Little bit of digging later, this might need to come with https://github.com/material-components/material-components-web/issues/5784 since drawer uses the text emphasis opacities.

We could figure out some workarounds... but that theming stuff is happening next and I'd rather get it in the right way than have to go back and take out a workaround since it's so close.

**Comment by asyncLiz** [comment] 2021-02-17 18:37
Going to clean up some issues and close this as a duplicate of https://github.com/material-components/material-components-web-components/issues/953. Subscribe to that issue for further updates!

**Closed by asyncLiz** 2021-02-17 18:37 UTC
Labels: Component: Drawer, Focus Area: Components, Severity: Medium, Type: Feature, Upstream, Why: Enable new use cases
