### ISSUE TITLE
mwc-icon-button doesn't lost focus UI after mouse click

### ISSUE THREAD

**Issue by Jack-Works** [material-components/material-components-web-components#1221] opened 2020-04-25 09:23 UTC
**Describe the bug**

The button always have `mdc-ripple-upgraded--background-focused` class when it has focus. This does make sense for keyboard users (`tab`, `shift-tab`, `space`) but confusing for mouse users (after click, the focus effect doesn't disappear)

```html
<mwc-icon-button icon="print" slot="actionItems"></mwc-icon-button>
```

**To Reproduce**
1. Click the button
2. The `focus` effect should disappear for mouse click even the button still hold the focus

**Expected behavior**
1. The `focus` effect always follow the `document.activeElement`

**Screenshots**
![image](https://user-images.githubusercontent.com/5390719/80276170-5ba9ac80-8719-11ea-93dd-1e6784283de9.png)

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by e111077** [comment] 2020-04-27 23:50
Hello, as you said, after clicking a button, it retains focus. A lengthy discussion with the design team says that this is the intended behavior for web unlike native android or ios.

As of now, this is spec, but the design team will come up with a reconciliation of the specs for this soon. Therefore I'm going to close this issue, but if the spec ends up changing (e.g. changed to touchstart / end is different from mousedown / up) we will implement it.

**Closed by e111077** 2020-04-27 23:50 UTC
Labels: Focus Area: Components, Type: Bug
