### ISSUE TITLE
mwc-textfield with charcounter throw error with undefined value

### ISSUE THREAD

**Issue by christophe-g** [material-components/material-components-web-components#1377] opened 2020-05-31 13:17 UTC
**Describe the bug**
setting value to undefined to `mwc-textfield`  (and `mwc-texarea`) with charcounter throw the following error (and in some cases breaks rendering)
```
mwc-textfield-base.js?module:251 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at HTMLElement.renderCharCounter (mwc-textfield-base.js?module:251)
    at HTMLElement.render (mwc-textfield-base.js?module:146)
    at HTMLElement.update (VM93 lit-element.js:155)
    at HTMLElement.performUpdate (updating-element.js?module:551)
    at HTMLElement._enqueueUpdate (updating-element.js?module:510)
```
The rationale and context is similar to the one described here https://github.com/material-components/material-components-web-components/issues/1116 (Polymer binding)

**To Reproduce**
https://codepen.io/christophe-g/pen/mdeNoqJ

**Comment by asyncLiz** [comment] 2020-05-31 18:10
This has been fixed in the latest version. If you change your import url versions to `@canary` you can see the new behavior.

Closing as duplicate of #1116

**Closed by asyncLiz** 2020-05-31 18:10 UTC
Labels: Focus Area: Components, Type: Bug
