### ISSUE TITLE
[Typography] Status?

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1806] opened 2020-09-13 14:41 UTC
Would just like to know what is the current status for the `Material Design` typography support, and to ensure that it will be fluid typography - meaning automatically resizing - accorindg to the viewport.

**Comment by asyncLiz** [comment] 2020-09-14 16:58
There has been no update, but if there is you'll be able to see it on https://github.com/material-components/material-components-web-components/issues/1050. I'd recommend subscribing to that issue for updates on the typography feature within MWC.

Keep in mind that MWC will provide typography support, but it will not provide automatic responsive size changes. That is an opinionated application responsibility.

Closing as a dupe of #1050.

**Closed by asyncLiz** 2020-09-14 16:58 UTC
Labels: Focus Area: Components, Type: Feature
