### ISSUE TITLE
mwc-top-app-bar doesn't horizontally resize when you open drawer

### ISSUE THREAD

**Issue by sujato** [material-components/material-components-web-components#780] opened 2020-01-15 22:51 UTC
**I'm submitting a:**

- [X] bug report
- [ ] feature request

**What OS are you using?**
Ubuntu 19.10

**What browser(s) is this bug affecting:**
Chromium 75

**Current behavior:**
When you open the drawer, the top app bar doesn't resize, it is pushed to the right, and anything in the actionItems slot gets pushed off screen. Centered headings also get pushed to the right.

**Expected behavior:**
Top app bar resizes when drawer is opened so that elements stay either centered or on the right where appropriate.

**Steps to reproduce:**
In the glitch demos you can see it by putting some content in the actionItems slot of the "Dismissible Drawer with header" example.

https://mwc-demos.glitch.me/demos/drawer.html

![Screencast from 16-01-20 09_37_16](https://user-images.githubusercontent.com/6112010/72478261-a4fa7e00-3845-11ea-9ee8-12fbaea82dd4.gif)

**Comment by e111077** [comment] 2020-02-06 00:03
duplicate of #705

**Closed by e111077** 2020-02-06 00:03 UTC
Labels: Component: Top App Bar, Type: Bug
