### ISSUE TITLE
Several Missing Packages in NPM

### ISSUE THREAD

**Issue by hen42** [material-components/material-components-web-components#162] opened 2018-11-10 08:24 UTC
Many of the components are not in npm, although the readme file tells me it is.

npm i @material/mwc-slider 

npm ERR! 404 Not Found: @material/mwc-slider@latest

Best regards

**Comment by elf-pavlik** [comment] 2018-11-10 14:34
duplicate of #76 ?

**Comment by hen42** [comment] 2018-11-10 18:16
yes, thanks duplicate of #76 .

Any updates on the roadmap, when will these components be released ?

**Closed** 2018-11-11 16:52 UTC
