### ISSUE TITLE
[mwc-textfield] Inherit `autocomplete` attribute

### ISSUE THREAD

**Issue by agektmr** [material-components/material-components-web-components#1148] opened 2020-04-16 01:14 UTC
**Is your feature request related to a problem? Please describe.**
`input` element comes with a convenient accessibility feature that helps user autofill information the browser remembered by using `autocomplete` attribute. I want to respect the same practice on `mwc-textfield`.

**Describe the solution you'd like**
Copy the value of `autocomplete` attribute assigned to `mwc-textfield` to the `input` element in the shadow DOM.

**Comment by asyncLiz** [comment] 2020-04-16 18:56
Duplicate of #82, we'll be working on form-based autocomplete in that issue.

**Closed by asyncLiz** 2020-04-16 18:56 UTC
Labels: Focus Area: Components, Type: Feature
