### ISSUE TITLE
Change form data to include name-value pairs for the 'custom-element'.

### ISSUE THREAD

**Issue by lotstar87** [material-components/material-components-web-components#668] opened 2019-11-29 07:19 UTC
** PLEASE READ THIS BEFORE FILING AN ISSUE **

**I'm submitting a:**

- [ ] bug report
- [x] feature request

**What OS are you using?**

MacOS Catalina (10.15.1)

**What browser(s) is this bug affecting:**

**Current behavior:**

form submit(formData) not includes key-value of child custom-elements
```html
<form id="form">
  <mwc-textfield name="name" value="value!"></mwc-textfield>
</form>
```
```js
var form = document.querySelector('#form')
var formData = new FormData(form)
console.log(Array.from(formData.entries())) // []
```

**Expected behavior:**

form submit(formData) includes key-value of child custom-elements
```html
<form id="form">
  <mwc-textfield name="name"  value="value!"></mwc-textfield>
</form>
```
```js
var form = document.querySelector('#form')
var formData = new FormData(form)
console.log(Array.from(formData.entries())) // [["name", "value!"]]
```

**Steps to reproduce:**

**Related code:**

```js
// insert any relevant code here or add a include a codepen
```

**Other information:**

see this, https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example

**Comment by e111077** [comment] 2020-02-05 23:39
Duplicate of #289

**Closed by e111077** 2020-02-05 23:39 UTC
Labels: Component: Text Field, Type: Enhancement
