### ISSUE TITLE
actionItems only show if drawer is modal

### ISSUE THREAD

**Issue by AlexanderLang** [material-components/material-components-web-components#705] opened 2019-12-16 18:32 UTC
**I'm submitting a:**
- [ x] bug report
- [ ] feature request

**What OS are you using?**
kubuntu 19.10

**What browser(s) is this bug affecting:**
chromium, firefox. (probably all browsers)

**Current behavior:**
When using a top-app-bar with a drawer, the icons in the "actionItems" slot only show if the drawer has type="modal"

**Expected behavior:**
The drawer type should not affect the actionItems in the top-app-bar

**Steps to reproduce:**
In the drawer demo, remove the type="modal" from the last example and see the icons on the right side of the top-app-bar disappear

**Comment by stephantabor** [comment] 2020-01-09 16:38
The issue is that the top app bar is staying as wide as the viewport when the drawer opens, and the action items are off screen to the left. 

----


### Examples

**current behavior:**

![current](https://user-images.githubusercontent.com/8570366/72086167-7d029c00-32d4-11ea-834c-300a3c262719.gif)


**desired behavior:**

![desired](https://user-images.githubusercontent.com/8570366/72086076-593f5600-32d4-11ea-8e9c-2df56e26a49f.gif)

**Comment by jonau** [comment] 2020-06-23 16:05
The issue is that `mdc-top-app-bar` is styled with `position: fixed`, which essential means that it has a width 100% of the window now.

For the `mdc-top-app-bar` a styling option with `position: absolute` might be viable. However I dont know what side effects there might be, especially with `mdc-top-app-bar-fixed`

**Comment by stephantabor** [comment] 2020-06-23 17:13
I maintain a customized fork of this (internal to my company) and its been a while but i'm pretty sure i just did a hack fix where the drawer will toggle a class in any slotted top-app-bars and then the top app bar does a `calc` to reduce width by drawer width. I think `position: absolute` had other issues

**Comment by e111077** [comment] 2020-07-09 19:46
fixed in #1508 you need to size top-app-bar to be 100% - the width of the drawer which can be adjusted with `--mdc-drawer-width`

e.g.

```css
mdc-drawer[open]:not(type="modal") {
  --mdc-top-app-bar-width: calc(100% - var(--mdc-drawer-width, 256px));
}
```

**Closed by e111077** 2020-07-09 19:46 UTC
Labels: Component: Drawer, Component: Top App Bar, Focus Area: Components, Severity: Medium, Type: Bug

**Comment by mahdiridho** [comment] 2020-07-11 11:49
What's about this issue [actionItems slot disappear on desktop media for standard bar with header](https://github.com/material-components/material-components-web-components/issues/1517) ?

It looks similar one, but different issue. I'm using standard header for desktop version and modal type for mobile version. The actionItems slot disappear for standard with header.

**Comment by e111077** [comment] 2020-07-13 15:30
Hello @mahdiridho, please read my comment above; it should solve your issue as well

**Comment by mahdiridho** [comment] 2020-07-13 18:02
I left a question above due to your solution doesn't work on my case, I have tried.

**Comment by e111077** [comment] 2020-07-13 18:11
I had a typo in the solution. The `:not` selector should be selecting the type attribute. Does that work?

**Comment by mahdiridho** [comment] 2020-07-13 19:11
Here, I created a demo to simulate my issue :

[mwc-top-app-bar slot actionItems disappear on desktop media](https://github.com/mahdiridho/actionItems-issue)

**Comment by e111077** [comment] 2020-07-13 19:13
it is not yet released; please install `@material/mwc-top-app-bar@canary` to see the changes

**Comment by mahdiridho** [comment] 2020-07-13 19:33
> it is not yet released; please install `@material/mwc-top-app-bar@canary` to see the changes

Well, It works but give me a new bug for the drawer style. It has about 10px margin now

![Screenshot from 2020-07-14 02-32-06](https://user-images.githubusercontent.com/10230037/87345505-591d5d00-c57a-11ea-9218-af0c02ecf4e3.png)
![Screenshot from 2020-07-14 02-32-23](https://user-images.githubusercontent.com/10230037/87345512-5ae72080-c57a-11ea-82b0-ed679cefd376.png)

**Comment by mahdiridho** [comment] 2020-07-13 19:47
For temporary solution, I adjust the drawer style to be : 

`
mwc-drawer {
  margin: -10px;
}
`

But, I think you will fix this part later?

Thanks

**Comment by asyncLiz** [comment] 2020-07-13 19:56
That looks like the body's default margin. Looking at your code, it doesn't look like you have anything to remove it. Try adding this to your index.html file:

```html
<style>body { margin: 0; }</style>
```

Since you're setting the width to 100% of the parent container, and the body has a margin, that's why the drawer isn't expanded to the full width of the viewport.

**Comment by mahdiridho** [comment] 2020-07-13 20:03
Ah I see, you're right @asyncLiz 

I have updated the demo repo for the final sample

Thanks everyone

**Comment by mahdiridho** [comment] 2020-07-20 18:32
> it is not yet released; please install `@material/mwc-top-app-bar@canary` to see the changes

Hi,

I get back my problem, either on my above demo or other projects. The above solution doesn't work anymore. You can try my demo link above. What happens?

**Comment by mahdiridho** [comment] 2020-07-21 05:59
Anybody knows why do @material/mwc-top-app-bar either @material/mwc-top-app-bar@canary have same problem now? Previously @material/mwc-top-app-bar@canary solved the issue.

**Comment by e111077** [comment] 2020-07-21 16:44
I unfortunately cannot repro. But in your example all mwc components should have the same version. Please update mwc-drawer's version to be the same as mwc-top-app-bar.

Note that our demos on github.io run at `@canary` in which i cannot reproduce your issue:

https://material-components.github.io/material-components-web-components/demos/

**Comment by mahdiridho** [comment] 2020-07-21 17:11
> I unfortunately cannot repro. But in your example all mwc components should have the same version. Please update mwc-drawer's version to be the same as mwc-top-app-bar.
> 
> Note that our demos on github.io run at `@canary` in which i cannot reproduce your issue:
> 
> https://material-components.github.io/material-components-web-components/demos/

Well, I have updated the mwc-drawer to be work @canary :

  `
    "dependencies": {
      "@material/mwc-drawer": "^0.18.0-canary.f6a6ca38.0",
      "@material/mwc-icon-button": "^0.17.2",
      "@material/mwc-top-app-bar": "^0.18.0-canary.f6a6ca38.0",
      "lit-element": "^2.3.1"
    }
  `
But same problem : 

![Screenshot from 2020-07-22 00-09-09](https://user-images.githubusercontent.com/10230037/88085129-9fdd0980-cbaf-11ea-8b5d-cbb240292391.png)
![Screenshot from 2020-07-22 00-08-52](https://user-images.githubusercontent.com/10230037/88085144-a66b8100-cbaf-11ea-8169-f256132ea536.png)

Strange.. previously it worked?

**Comment by e111077** [comment] 2020-07-21 19:44
I am still unable to reproduce this issue. Can you please provide a live reproduction case? You can fork / remix and edit https://mwc-demos.glitch.me/ with the link at the top of the page (don't forget to set all the dependencies to `@canary`).

Additionally, this application already uses mwc-top-app-bar-fixed. You just need to add the drawer and styling

**Comment by mahdiridho** [comment] 2020-07-22 03:58
I provided the demo on separate repo, you can just clone, install, and serve the demo app to reproduce the issue : 

[https://github.com/mahdiridho/actionItems-issue](https://github.com/mahdiridho/actionItems-issue)

I'm implementing property binding for the mwc-drawer type and the mwc-top-app-bar size

**Comment by mahdiridho** [comment] 2020-07-22 04:07
Previous one (about a week ago), my dependencies work like so : 

`
"dependencies": {
    "@material/mwc-drawer": "^0.17.2",
    "@material/mwc-icon-button": "^0.17.2",
    "@material/mwc-top-app-bar": "^0.18.0-canary.efdfbc21.0",
    "lit-element": "^2.3.1"
  }
`

And it solved my issue. This week I was implementing the solution to another project but doesn't work. Then I back to my demo repo to compared, strange.. It didn't work as well with my original demo.

The update dependencies doesn't work as well, now I stuck how to resolve it.

**Comment by mahdiridho** [comment] 2020-07-22 05:21
> I am still unable to reproduce this issue. Can you please provide a live reproduction case? You can fork / remix and edit https://mwc-demos.glitch.me/ with the link at the top of the page (don't forget to set all the dependencies to `@canary`).
> 
> Additionally, this application already uses mwc-top-app-bar-fixed. You just need to add the drawer and styling

Well, I just remix the glitch demo here : 

[https://glitch.com/~unmarred-pewter-mayflower](https://glitch.com/~unmarred-pewter-mayflower)

Now, you can see and reproduce the issue

**Comment by e111077** [comment] 2020-07-22 16:33
This is due to your use of semantic versioning. Here is a working example:

https://glitch.com/edit/#!/quasar-fearless-magazine?path=package.json%3A12%3A30

in your package.json you have:

`"@material/mwc-top-app-bar": "^0.18.0-canary.f6a6ca38.0",`

The `^` means to go up to the latest major version which in this case resolves to:

`0.18.0-canary.fd970958.0`

which is in fact an older canary commit. You need to pin it to that version using

`"@material/mwc-top-app-bar": "=0.18.0-canary.f6a6ca38.0",`

or if you don't mind the uncertainty

`"@material/mwc-top-app-bar": "canary",`

which will always be the latest version. Additionally, all components in our component set should be on the same version to prevent code duplication and possible web component name registry clashes. You should also align the version of `@material/mwc-icon-button`

**Comment by mahdiridho** [comment] 2020-07-22 18:50
I see

I did npm i -s @material/mwc-top-app-bar@canary and it set to semantic version.

It works back now, thanks
