### ISSUE TITLE
mwc-check-list-item checked vs. selected

### ISSUE THREAD

**Issue by nicolasr75** [material-components/material-components-web-components#2075] opened 2021-01-13 02:09 UTC
I am a little surprised by the behavior of `mwc-check-list-item`.
It looks like the state of the checkbox serves only as another indication of item selection which is already indicated by its highlighing. Usually I use check list boxes to have the checkboxes indicate some boolean property of the items.

Consider the following example:

My items have properites like `Name, Description, Visible`, etc.
To allow my user to edit these items I would use a list box and when an item is selected, a form with some input fields would allow the user to change the properties of the selected item. Now my motivation to use a check list box would be to make the `Visible` property more apparent and easier to edit. But then the state of the check box would have to be decoupled from the selection of the item.

Is something like this possible or is the check box always meant to be in sync with the item selection?

It would be nice to have both options but I admit that this would probably require some redesign. Maybe it would even contradict the material design guidelines?

**Comment by asyncLiz** [comment] 2021-01-15 21:37
This is intentional per the Material Design guidelines. Both list items and checkboxes are actionable touch targets, and selection should be the main action of a list item when a checkbox is presented, rather than presenting multiple selection actions simultaneously (which can be confusing to the user).

For your use case, consider displaying other interactive content to indicate the `visible` state of the item, such as an icon toggle button instead of checkbox. This will achieve the same effect without the preconception around checkbox and selection state.

Keep in mind though, that caution should be used when introducing multiple action areas into a list item. Simpler is usually better, so ask if it's really necessary or if there's another UX (such as opening the list item to modify the state) that would be equally appropriate and potentially less confusing if there are several touch targets on the page that could overwhelm or confuse the user if they accidentally press them.

Hope this helps! I'm going to close this issue since it's currently working as intended.

**Closed by asyncLiz** 2021-01-15 21:37 UTC
Labels: Focus Area: Components, Type: Feature

**Comment by nicolasr75** [comment] 2021-01-15 22:21
Thanks for taking the time to share your thoughts about this! I think my ideas come from a time before touch displays ;-) After checking that even Windows Explorer uses checkboxes to ease multi selection, I agree that my way would probably be more confusing these days. I will find another solution.
