### ISSUE TITLE
mwc-top-app-bar width inside mwc-drawer  

### ISSUE THREAD

**Issue by GeorgeousCode** [material-components/material-components-web-components#1063] opened 2020-04-01 19:30 UTC
**Describe the bug**

When mwc-drawer is open the "actionItems" slots in mwc-top-app-bar are gettin out of the window.

**Expected behavior**

The mwc-top-app-bar should be resize following its parent.

**Code**

<img width="923" alt="Capture d’écran 2020-04-01 à 21 13 40" src="https://user-images.githubusercontent.com/59330850/78177698-cc351480-745e-11ea-8246-132f3b230035.png">

**Screenshots**

***closed drawer***
<img width="1680" alt="Capture d’écran 2020-04-01 à 21 28 06" src="https://user-images.githubusercontent.com/59330850/78178328-bf64f080-745f-11ea-844d-f672b4dc5521.png">
***opened drawer (icons are hidden).***
<img width="1680" alt="Capture d’écran 2020-04-01 à 21 28 13" src="https://user-images.githubusercontent.com/59330850/78178322-be33c380-745f-11ea-986e-4f2b5ad748e0.png">

**Comment by sujato** [comment] 2020-04-07 21:37
Dupe of #705 . i know, because I made my own dupe some time ago! Which suggests that the title of 705 does not describe the issue very well.

**Comment by dfreedm** [comment] 2020-04-08 22:34
Yep, duplicate of #705.

**Closed by dfreedm** 2020-04-08 22:34 UTC
Labels: Component: Top App Bar, Focus Area: Components, Severity: Medium, Type: Bug
